# Generated by Django 5.2.5 on 2025-10-12 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-ultimo_mensaje_en', '-creado']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='conversation',
            new_name='conversacion',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_chat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ConversationParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='chat.conversation')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias_chat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation_participantes',
                'unique_together': {('conversacion', 'usuario')},
            },
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='conversations', through='chat.ConversationParticipante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ConversationMember',
        ),
    ]
