# Generated by Django 5.2.5 on 2025-10-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud en grados decimales', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud en grados decimales', max_digits=9, null=True),
        ),
    ]
