# Generated by Django 5.2.5 on 2025-09-07 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('Pasaporte', 'Pasaporte')], default='CC', max_length=20)),
                ('numero_documento', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('pais', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=80)),
                ('direccion_exacta', models.CharField(blank=True, max_length=255)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incompleto'), ('VERIFIED', 'Verificado')], default='INCOMPLETE', max_length=20)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
